name: baby-1l-run-3
channels:
  - conda-forge
dependencies:
  - python
  - openmc # add version tag
  - openmc-plotter
  - numpy # add version tag
  - scipy # add version tag
  - matplotlib # add version tag
  - plotly
  - sympy
  - pandas
  - pint-pandas
  - nbconvert
  - ipykernel
  - pint
  - h5py
  - pytables
  - pip
  - pip:
      - git+https://github.com/libra-project/libra-toolbox@final-push
      - openmc_data_downloader
      - matplotlib-label-lines
      - h-transport-materials
